//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E3DBPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public int BidID { get; set; }
        public int SubProjectID { get; set; }
        public int CompanyID { get; set; }
        public System.DateTime BidDate { get; set; }
        public string BidText { get; set; }
        public string BidLimitations { get; set; }
        public decimal BidAmt { get; set; }
        public string BidStatus { get; set; }
        public bool Deleted { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> LastViewDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual SubProject SubProject { get; set; }
    }
}
