//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E3DBPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BlogComment
    {
        public int PostCommentID { get; set; }
        public int PostID { get; set; }
        public string PostCommentAuthor { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> PostCommentDate { get; set; }
        public string PostCommentContent { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> PostCommentCompanyID { get; set; }
    
        public virtual BlogPost BlogPost { get; set; }
    }
}
