//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E3DBPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentID { get; set; }
        public int SubProjectID { get; set; }
        public string DocumentTitle { get; set; }
        public string DocumentText { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public int CompanyID { get; set; }
        public string Location { get; set; }
        public string Notes { get; set; }
    
        public virtual SubProject SubProject { get; set; }
        public virtual Company Company { get; set; }
    }
}
