//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E3DBPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public int VendorID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> SKU { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> VendorItemID { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public Nullable<decimal> Price4 { get; set; }
        public Nullable<decimal> Price5 { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<int> InStock { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Featured { get; set; }
        public Nullable<decimal> ItemNW { get; set; }
        public string Limage { get; set; }
        public string Simage { get; set; }
        public string Timage { get; set; }
        public string Pic01 { get; set; }
        public string Pic02 { get; set; }
        public string Pic03 { get; set; }
        public string WebLink { get; set; }
        public bool Outlet { get; set; }
        public Nullable<int> OrderMin { get; set; }
        public Nullable<int> OrderInc { get; set; }
        public Nullable<int> BoxID { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<int> Ranking { get; set; }
    
        public virtual ItemBox ItemBox { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ItemBox ItemBox1 { get; set; }
    }
}
