//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E3DBPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public int FromID { get; set; }
        public Nullable<int> ToID { get; set; }
        public string ToEmail { get; set; }
        public string ToFName { get; set; }
        public string ToLName { get; set; }
        public Nullable<int> ToCompany { get; set; }
        public string MessageSubject { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public bool DBPImail { get; set; }
        public string FromEmail { get; set; }
        public string FromFName { get; set; }
        public string FromLName { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public int FromCompany { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
