//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E3DBPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public int PaymentMethodID { get; set; }
        public int CompanyID { get; set; }
        public int PaymentType { get; set; }
        public string PaymentMethodName { get; set; }
        public string AccountNumber { get; set; }
        public string RoutingNumber { get; set; }
        public string BankName { get; set; }
        public Nullable<int> ExpirationMonth { get; set; }
        public Nullable<int> ExpirationYear { get; set; }
        public string PayeeName { get; set; }
        public string PayeeAddress { get; set; }
        public string PayeeCity { get; set; }
        public string PayeeState { get; set; }
        public string PayeeZip { get; set; }
        public string PayeeCountry { get; set; }
        public string OtherInfo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastActivityDate { get; set; }
        public Nullable<bool> SetAsDefault { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
