//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E3DBPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePlan
    {
        public int ServicePlanID { get; set; }
        public string ServicePlanName { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string Seats { get; set; }
        public string Storage { get; set; }
        public string FeatureA { get; set; }
        public string FeatureB { get; set; }
        public string FeatureC { get; set; }
        public string FeatureD { get; set; }
        public string FeatureE { get; set; }
        public Nullable<decimal> AddSeatCost { get; set; }
        public Nullable<decimal> MontlhyCost { get; set; }
        public Nullable<decimal> AnnualCost { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
