//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E3DBPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int TeamRecordID { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Title { get; set; }
    }
}
