//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E3DBPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemBox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemBox()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int BoxID { get; set; }
        public string BoxDescription { get; set; }
        public Nullable<decimal> BoxWidth { get; set; }
        public Nullable<decimal> BoxLength { get; set; }
        public Nullable<decimal> BoxHeight { get; set; }
        public Nullable<decimal> BoxNW { get; set; }
        public Nullable<decimal> BoxCF { get; set; }
        public Nullable<bool> InnerOuter { get; set; }
        public Nullable<int> InnerBoxFor { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Zone01 { get; set; }
        public Nullable<decimal> Zone02 { get; set; }
        public Nullable<decimal> Zone03 { get; set; }
        public Nullable<decimal> Zone04 { get; set; }
        public Nullable<decimal> Zone05 { get; set; }
        public Nullable<decimal> Zone06 { get; set; }
        public Nullable<decimal> Zone07 { get; set; }
        public Nullable<decimal> Zone08 { get; set; }
        public Nullable<decimal> Zone09 { get; set; }
        public Nullable<decimal> Zone10 { get; set; }
        public Nullable<decimal> Zone11 { get; set; }
        public Nullable<decimal> Zone12 { get; set; }
        public Nullable<decimal> Zone13 { get; set; }
        public Nullable<decimal> Zone14 { get; set; }
        public Nullable<decimal> Zone15 { get; set; }
        public bool RuralZone { get; set; }
        public bool InternationalZone { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
    }
}
