//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E3DBPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderLines = new HashSet<OrderLine>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int OrderID { get; set; }
        public int CompanyID { get; set; }
        public string CustOrderNumber { get; set; }
        public string OrderStatus { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> ShipToAddressID { get; set; }
        public Nullable<int> ShipperID { get; set; }
        public string ShipperTracking { get; set; }
        public Nullable<decimal> ProductTotal { get; set; }
        public Nullable<decimal> WebShipping { get; set; }
        public Nullable<decimal> ActualShipping { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
        public Nullable<decimal> Discounts { get; set; }
        public bool Fulfilled { get; set; }
        public bool Deleted { get; set; }
        public string Notes { get; set; }
        public bool Active { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
