//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E3DBPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int OrderID { get; set; }
        public int CompanyID { get; set; }
        public decimal PaymentAmt { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentType { get; set; }
        public string PayerID { get; set; }
        public string TransID { get; set; }
        public string TransStatus { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string BankAccount { get; set; }
        public string BankRouting { get; set; }
        public string CardType { get; set; }
        public string CardNumber { get; set; }
        public string CardExMo { get; set; }
        public string CardExYr { get; set; }
        public string CardCVCC { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
