//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E3DBPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public string ProjectStatus { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> BidOpenDate { get; set; }
        public Nullable<System.DateTime> BidCloseDate { get; set; }
        public int CompanyID { get; set; }
        public bool Deleted { get; set; }
        public bool Active { get; set; }
        public string Notes { get; set; }
        public bool Complete { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public Nullable<int> AcceptedBid { get; set; }
        public Nullable<int> AcceptedCompany { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string SiteAddress1 { get; set; }
        public string SiteAddress2 { get; set; }
        public string SiteAddressCity { get; set; }
        public string SiteAddressState { get; set; }
        public string SiteAddressZip { get; set; }
        public string SiteAddressCountry { get; set; }
        public bool IsSubProject { get; set; }
        public Nullable<int> SubProjectOf { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
